### ISSUE TITLE
Level And Auto Mode

### ISSUE THREAD

**Issue by spin877** [bderleta/vevor-ble-bridge#2]
Please implement a button for the manual and automatic mode. 
Here are the commands referring to my code:

cmd5 = common_bytes + bytearray([0x02, 0x01, 0x00, 0x31]) # Manual Mode Level
cmd6 = common_bytes + bytearray([0x02, 0x02, 0x00, 0x32]) # Automatic Mode

compared to your code, something like this should happen

#mode_state = 1 --> Level
#mode_state = 2 -- > Auto

def set_mode(self, mode_state):
`   ` self._send_command(2, mode_state, 85)  

but I don't know how to implement it

**Comment by bderleta** [comment]
Yes, it's on my roadmap, just I need to work out how to not break the controls on the Home Assistant side too much when switching modes. It's not an issue with sending commands to the heater at all, we already know the full command set.

The "problem" (not a problem really, just an inconvenience) is that I need to manage availability states for those controls to prevent erratic operation, and this requires a bit of real life testing.

**Comment by bderleta** [comment]
https://github.com/bderleta/vevor-ble-bridge/commit/2505ac8b9f0297c5d16209fdf441c537bfeb4e81
