### ISSUE TITLE
HassOS Addon

### ISSUE THREAD

**Issue by Spyder2005** [bderleta/vevor-ble-bridge#7]
Hey Guys, 

nice work! Is it possible to make the extension available here as a HassOs addon? 

If I understand correctly, I can't run docker-compose on a HassOS? However, all addons are apparently based on docker and so it should not be a problem to start your extension if it is built as an add-on?

Thanks in advance!

**Comment by bderleta** [comment]
Hey, I have no experience with HassOS, unfortunately, and no time to research it - as I use HomeAssistant on shared machines with other software running. Feel free to play, compose is only a way to start the container, if you can build the container it can be started without compose, using `docker run` call.
