### ISSUE TITLE
what hardware do i need?

### ISSUE THREAD

**Issue by abercrombie1892** [bderleta/vevor-ble-bridge#8]
I also have a diesel heater that can be controlled via Bluetooth via the app. What hardware do I need so that the home assistant connects to the heating? an ESP32? ESPHome? Thank you very much for this project

**Comment by bderleta** [comment]
Regarding this project, you need a single board computer or other machine capable of running Docker, with bluetooth adapter and network connectivity. This project won't work on an ESP platform, but there are another bridges working with ESPHome. I tested my project on Raspberry Pi 5, but any properly equipped SBC like BananaPI or OrangePI would work, but I had various problem with drivers on those platforms.

SBC with this container just acts like a relay node between heater (so it must be placed close to it, as BLE has quite low range) and your existing HomeAssistant setup, with already running and configured MQTT broker. The SBC itself of course can be the node running MQTT broker, and even whole HomeAssistant setup, only mandatory thing is being in the range of BLE (and having BLE-capable adapter onboard).
